ALTER TABLE post ADD COLUMN is_anonymous BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE comment ADD COLUMN is_anonymous BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE reply ADD COLUMN is_anonymous BOOLEAN DEFAULT FALSE NOT NULL;
