import 'package:flutter/material.dart';

const PRIMARY_COLOR = Color(0xFFAA71D8);
const PRIMARY10_COLOR = Color(0xFFF7F1FF);
const PRIMARY20_COLOR = Color(0xFFF8E4FF);
const PRIMARY50_COLOR = Color(0xFFCC96FE);
const BODY_TEXT_COLOR = Color(0xFFF6F6F6);
const INPUT_BG_COLOR = Color(0xFFFBFBFB);
const INPUT_BORDER_COLOR = Color(0xFFF3F2F2);
const MAJOR_SELECT_COLOR = Color(0xFFF2F2F2);
const CATEGORY_COLOR = Color(0xFFBA84FF);
const BOARD_CARD_COLOR = Color(0xFFFAFAFA);
const BOARD_CARD_TIME_COLOR = Color(0xFF828282);

const TEXT_FIELD_COLORS = [
  Color(0xFFDE81FF),
  Color(0xFF89EAFF),
  Color(0xFFD151FF),
  Color(0xFFE7BBFF),
  Color(0xFFFFFA8C),
  Color(0xFFC590FF),
  Color(0xFF89EAFF),
  Color(0xFFDE81FF),
  Color(0xFFECB7FF),
];

const TEXT_FIELD_SEND_COLOR = Color(0xFFDE81FF);
const BOX_LINE_COLOR = Color(0xFFE0DDDD);
const HEART_BG_COLOR = Color(0xFFFFF5F5);
const FAVORITE_BG_COLOR = Color(0xFFFFFBE8);
const FAVORITE_COLOR = Color(0xFFFFD600);
const STUDY_PERSON_BACK_COLOR = Color(0xFFEAEAEA);
const STUDY_PERSON_COLOR = Color(0xFFC318FF);
const TAG_COLOR = Color(0xFF2839D2);
const CLOUD_COLOR = Color(0xFF787878);
const ACTIVE_COLOR = Color(0xFF63B6FF);
const INACTIVE_COLOR = Color(0xFF3CBB27);
const MY_COMMENT_TEXT_COLOR = Color(0xFF0087FF);
const MY_COMMENT_COLOR = Color(0xFFE9F5FF);
