spring:
  profiles:
    group:
      "local": "dev"

  config:
    import:
      - classpath:application-security.yml
      - classpath:application-dev.yml
      - classpath:application-test.yml
      - classpath:application-prod.yml
---

