spring:
  config:
    activate:
      on-profile: "dev"

  flyway:
    enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dclass?serverTimezone=UTC
    username: dclass-user
    password: password


  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 10

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret: "1cf848f58e0e538db479ee4c0ea6df2e152da2688a0f8ed63aeb3e17359c521122ad20efc5f28cd6943ef86363c17f72eb4c7482bdae6b749f80cc9e23a07fe4"

springdoc:
  packages-to-scan: com.dclass.backend.ui
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
---